# Generated by Django 5.1.3 on 2024-11-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_student_teacher_student_teachers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='student', to='school.teacher', verbose_name='Учителя'),
        ),
    ]
